# Generated by Django 4.2.17 on 2024-12-27 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('enquiry_description', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='unread', max_length=50)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
