# Generated by Django 4.2.17 on 2024-12-26 18:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('editing', 'Editing and Proofreading'), ('formatting', 'Book Formatting'), ('webdev', 'Web Development')], max_length=20)),
                ('profile_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('word_count_range', models.CharField(blank=True, max_length=100, null=True)),
                ('turnaround_time', models.CharField(blank=True, max_length=100, null=True)),
                ('formats_supported', models.CharField(blank=True, max_length=200, null=True)),
                ('technologies_used', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
