# Generated by Django 4.2.17 on 2024-12-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_order_word_count_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('editing', 'Editing and Proofreading'), ('formatting', 'Book Formatting'), ('webdev', 'Web Development'), ('author', 'Author Services')], max_length=20),
        ),
    ]
