# Generated by Django 4.2.17 on 2024-12-31 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='min_price',
        ),
    ]
