# Generated by Django 4.2.17 on 2024-12-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_price_service_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=999.99, max_digits=8),
        ),
    ]
