# Generated by Django 4.2.17 on 2025-01-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_max_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='word_count_range',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=8),
        ),
    ]
