# Generated by Django 4.2.17 on 2024-12-27 22:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testimonial_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsWork',
            fields=[
                ('author', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('img', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('work_description', models.TextField()),
                ('work_url', models.URLField(blank=True)),
                ('work_location', models.CharField(blank=True, choices=[('online_bookstore', 'Online Bookstore'), ('online_free', 'Online Free'), ('print_bookstore', 'Print Bookstore'), ('library', 'Library'), ('other', 'Other')], default='online_bookstore', max_length=200)),
            ],
        ),
    ]
